### ISSUE TITLE
20160823

### ISSUE THREAD

**Issue by xhe123** [RHQE/pylarion-cmd#5]
Sim Zacks has posted comments on this change.

Change subject: Add the command line tool: pylarion-cmd
......................................................................

Patch Set 2: Code-Review-1

(18 comments)

**https://code.engineering.redhat.com/gerrit/#/c/80881/2/scripts/pylarion-cmd
File scripts/pylarion-cmd:**
- [x]  Line 18: .
  remove period
- [x]  Line 84:     LOCAL_CONFIG = os.path.expanduser("~") + "/.pylarion"
     :     condict = Config().getconf(LOCAL_CONFIG)
  Please see base_polarion.py for example on loading config.
  Settings in the local dir override settings in the home dir, which overrides settings in the base dir. It has to check all of them
- [x]  Line 90:     # get all documents in space
     :     if (not query) and is_document:
     :         docs = list_obj.list_all_documents_under_space()
     :         list_obj.print_documents(docs,
     :                                  fields=['document_id',
     :                                          'document_name',
     :                                          'author',
     :                                          'updated',
     :                                          'updated_by'])
     :     # query document
     :     elif is_document and query:
     :         docs = list_obj.list_documents_by_query(query)
     :         list_obj.print_documents(docs,
     :                                  fields=['document_id',
     :                                          'document_name',
     :                                          'author',
     :                                          'updated',
     :                                          'updated_by'])
     :     # get workitems in doc
     :     elif document and workitem:
     :         wis = list_obj.list_workitems_in_doc('%s/%s' % (condict['con_space'],
     :                                                         document))
     :         list_obj.print_workitems(wis)
     :
     :     # get links of testcase
     :     elif links and testcase:
     :         list_obj.print_links_for_testcase(testcase)
     :
     :     # get links of requirement
     :     elif links and requirement:
     :         list_obj.print_links_for_requirement(requirement)
     :
     :     # get runs by query
     :     elif (not is_document) and (not template) and query:
     :         list_obj.print_runs_by_query(query)
     :
     :     # get templates by query
     :     elif (not is_document) and (query and template):
     :         list_obj.print_templates_by_query(query)
     :
     :     # get steps for testcase
     :     elif steps and testcase:
     :         list_obj.print_steps_for_testcase(testcase)
     :
     :     # get testcases from run/template
     :     elif run and workitem:
     :         list_obj.print_testcases_from_run(run)
     :
     :     # get plan ids
     :     elif plan_ids:
     :         list_obj.print_plan_ids(plan_ids)
     :
     :     else:
     :         click.echo('Please get usage: pylarion-cmd list --help')
  
  Might be more readable like this.
  I also noticed there is no query for test cases that are # not in documents.

if is_document:
    if query:
        # get all documents in space
        docs = list_obj.list_all_documents_under_space()
    else:
        # query document
               docs = list_obj.list_documents_by_query(query)
    list_obj.print_documents(docs,
                             fields=['document_id',
                                     'document_name',
                                     'author',
                                     'updated',
                                     'updated_by'])
elif links:
    # get links of testcase
    if testcase:
        list_obj.print_links_for_testcase(testcase)
    # get links of requirement
    elif requirement:
        list_obj.print_links_for_requirement(requirement)
elif workitem:
    # get workitems in doc
    if document:
        wis = list_obj.list_workitems_in_doc('%s/%s' % (condict['con_space'],
                                                        document))
        list_obj.print_workitems(wis)
    elif run:
        # get testcases from run/template
        list_obj.print_testcases_from_run(run)
elif query and template:
    # get templates by query
    list_obj.print_templates_by_query(query)
elif query:
    # get runs by query (when template not specified)
    list_obj.print_runs_by_query(query)
elif plan_ids:
    # get plan ids
    list_obj.print_plan_ids(plan_ids)
else:
    click.echo('Please get usage: pylarion-cmd list --help')
- [x]  Line 209:     LOCAL_CONFIG = os.path.expanduser("~") + "/.pylarion"
      :     condict = Config().getconf(LOCAL_CONFIG)
- See above.
- This shouldn't be defined multiple times.
- [x]  Line 215:     # update single run
      :     if run and (not result) and (not status):
      :         update_obj.update_runs(run, template, plannedin, assignee)
      :
      :     # update one case result for run
      :     elif run and result and testcase:
      :         update_obj.update_1_result_for_runs(run, testcase, result,
      :                                             assignee, comment)
      :
      :     # update all cases result for run(s)
      :     elif run and result and (not testcase):
      :         update_obj.update_all_results_for_runs(run, result,
      :                                                assignee, comment)
      :
      :     # update status for run(s)
      :     elif run and status:
      :         update_obj.update_status_for_runs(run, status)
      :
      :     else:
      :         click.echo('Please get usage: pylarion-cmd list --help')
  Maybe more readable

if run:
    if testcase:
        if result:
            # update one case result for run
            update_obj.update_1_result_for_runs(run, testcase, result,
                                            assignee, comment)
        else:
            # update all cases result for run(s)
            update_obj.update_all_results_for_runs(run, result,
                                               assignee, comment)
    elif status:
        # update status for run(s)
        update_obj.update_status_for_runs(run, status)
    elif not result:
        # update single run
        update_obj.update_runs(run, template, plannedin, assignee)
else:
    click.echo('Please get usage: pylarion-cmd list --help')

**https://code.engineering.redhat.com/gerrit/#/c/80881/2/src/pylarion/cli/cmd.py
File src/pylarion/cli/cmd.py:**
- [x]  Line 56:         self.conf_space = space
     :         self.conf_plannedin = plannedin
  These are never used. Do they have a purpose?
- [x]  Line 59:     def getconf(self, confile):
  why not do all of this in the **init** and automatically import the config file in the same manner as base_polarion.py?
- [x]  Line 64:         condict['con_space'] = cfile.get('cmd', 'space')
     :         condict['con_plannedin'] = cfile.get('cmd', 'plannedin')
     :         condict['assignee'] = cfile.get('cmd', 'assignee')
  Are these really attributes that you want in the config file?
  Think about other use cases.
- Is everyone who uses the cli only going to work on a single space?
- Do you want the user to have to change the config file every time s/he wants information on a different plan?
- I don't see any use of con_plannedin or con_assignee. Do they have a purpose?

I would recommend using config vars transparently to the controller, meaning instantiate it in this file and use it for each class internally. So instead of passing a config var to the class, have the class use that config value as a default.
- [x]  Line 72: update
  maybe list?
- [x]  Line 80: update
  list
- [x]  Line 91: fields=None
  you accept fields as a parameter and overwrite it right away. If the user passes in a fields, it will not have any meaning
- [x]  Line 105: is_sql=False
  Will the CLI give an option to write SQL queries? right now there is no flag for that.
- [x]  Line 106: fields=None
  fields is overwritten
- [x]  Line 127: Document.default_project
  is CLI always used with default project?
- [x]  Line 150: TestCase.default_project
  same as above
- [x]  Line 304: for run in runs.split(','):
  This will print Done! for each run
- [x]  Line 326:             rec.executed = datetime.datetime.now()
      :             rec.executed_by = user
      :             rec.result = result
      :             rec.comment = comment
  these should be inside the if below
- [x]  Line 339:     def update_1_result_for_runs(self,
      :                                  runs,
      :                                  testcase,
      :                                  result,
      :                                  user,
      :                                  comment):
  Is this a valid use case?
## 

To view, visit https://code.engineering.redhat.com/gerrit/80881
To unsubscribe, visit https://code.engineering.redhat.com/gerrit/settings

Gerrit-MessageType: comment
Gerrit-Change-Id: I198a96ab03171e9c923c0d5c9eafba271884ed3e
Gerrit-PatchSet: 2
Gerrit-Project: pylarion
Gerrit-Branch: master
Gerrit-Owner: Xiaonan He xhe@redhat.com
Gerrit-Reviewer: CI OPs Jenkins <alivigni+ciops@redhat.com>
Gerrit-Reviewer: Linqing Lu lilu@redhat.com
Gerrit-Reviewer: Sim Zacks szacks@redhat.com
Gerrit-HasComments: Yes

**Comment by lulinqing** [comment]
Fixed #8
